# -*- coding: utf-8 -*-
"""search-history-analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WjSyDcS0Hm215bU3lAcXTOjlQFSZN8_F
"""

import pandas as pd
df = pd.read_json("/content/watch-history.json")

del df["header"]
del df["products"]
del df["details"]

df.to_csv("watct-history-cleaned.csv")